<?php

namespace app\admin\controller;

use think\Controller;

class Index extends Controller
{

    /**
     * 构造方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $sessionId = session('token');
        $cookieId  = session('token');
        if(empty($sessionId) || $sessionId != $cookieId){
            $this->redirect('admin/login/index');die;
        }
    }

    /**
     * 显示首页
     *
     * @return \think\Response
     */
    public function index()
    {
        $userName  = cookie('userName');
        $userId  = cookie('userId');
        $data = model('User')->userLogin(['userId'=>$userId]);
        return view('account/account',['userName' => $userName,'data'=>$data]);
    }

}
